/*
-- Query: SELECT * FROM bebidas_chabas.produto
-- Date: 2023-03-31 21:17
*/
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (1,'Vodka Absolut','Absolut Company','ML',1000,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (2,'Whisky Johnnie Walker Black Label','Diageo','ML',1000,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (3,'Tequila Don Julio Reposado','Diageo','ML',750,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (4,'Gin Beefeater','Pernod Ricard','ML',750,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (5,'Rum Bacardi Superior','Bacardi Limited','ML',750,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (6,'Cachaça Ypióca Ouro','Ypióca Agroindustrial','ML',1000,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (7,'Vinho tinto Château Margaux','Château Margaux','ML',750,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (8,'Vinho branco Sauvignon Blanc Cloudy Bay','Cloudy Bay Vineyards','ML',750,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (9,'Vinho rosé Whispering Angel','Château d\'Esclans','ML',750,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (10,'Champanhe Moët & Chandon Brut Impérial','Moët & Chandon','ML',750,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (11,'Cerveja belga Chimay Blue','Abbaye de Scourmont','ML',750,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (12,'Cerveja alemã Weihenstephaner Hefe Weissbier','Bayerische Staatsbrauerei Weihenstephan','ML',500,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (13,'Cerveja inglesa Fuller\'s ESB','Fuller\'s Brewery','ML',500,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (14,'Cerveja americana Sierra Nevada Pale Ale','Sierra Nevada Brewing Co.','ML',355,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (15,'Cerveja mexicana Corona Extra','Grupo Modelo','ML',355,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (16,'Cerveja brasileira Wäls Niobium','Cervejaria Wäls','ML',375,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (17,'Cerveja portuguesa Super Bock Stout','Super Bock Group','ML',330,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (18,'Cerveja japonesa Kirin Ichiban','Kirin Brewery Company','ML',330,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (19,'Cerveja holandesa La Trappe Quadrupel','Bierbrouwerij De Koningshoeven','ML',330,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (20,'Vermute Carpano Antica Formula','Francesco Carpano','ML',1000,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (21,'Aperol Spritz','Campari Group','ML',1000,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (22,'Licor de café Kahlúa','Pernod Ricard','ML',750,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (23,'Licor de menta Creme de Menthe Peppermint','Marie Brizard','ML',700,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (24,'Licor de anis Pernod','Pernod Ricard','ML',700,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (25,'Licor de cereja Cherry Heering','Peter F. Heering','ML',700,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (26,'Licor de laranja Grand Marnier','Campari Group','ML',700,0);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (27,'Água com gás','Schweppes','ML',2000,100);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (28,'Água sem gás','Crystal','ML',2000,150);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (29,'Água tônica','Schweppes','ML',1000,80);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (30,'Refrigerante Coca-Cola','Coca-Cola Company','ML',2000,120);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (31,'Refrigerante Pepsi','PepsiCo','ML',2000,80);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (32,'Suco de laranja','Del Valle','ML',1000,50);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (33,'Suco de uva','Maguary','ML',1000,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (34,'Suco de maçã','Juxx','ML',1000,40);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (35,'Chá mate','Lipton','ML',2000,60);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (36,'Chá verde','Nestea','ML',2000,50);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (37,'Chá de hibisco','Twinings','ML',1000,40);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (38,'Leite integral','Nestlé','ML',1000,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (39,'Leite desnatado','Itambé','ML',1000,15);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (40,'Leite de coco','Sococo','ML',200,50);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (41,'Iogurte natural','Nestlé','ML',500,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (42,'Iogurte de frutas','Danone','Unidades',1,60);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (43,'Queijo minas frescal','Tirolez','Gramas',500,40);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (44,'Manteiga','Aviação','Gramas',200,25);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (45,'Cream cheese','Philadelphia','Gramas',150,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (46,'Patê de frango','Perdigão','Gramas',100,50);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (47,'Gelo em cubos','Iceberg','Quilos',1,100);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (48,'Gelo triturado','Polar','Quilos',1,50);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (49,'Gelo em escamas','Arctic','Quilos',1,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (50,'Gelo seco','Dry Ice','Quilos',1,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (51,'Gelo em pacotes','Crystal Ice','Unidades',10,80);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (52,'Gelo em barras','Ice Bar','Quilos',2,40);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (53,'Gelo em esferas','Ice Ball','Unidades',1,60);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (54,'Gelo colorido','Crazy Ice','Unidades',50,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (55,'Gelo em formato de coração','Love Ice','Unidades',5,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (56,'Gelo comestível','Freezable','Unidades',10,15);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (57,'Whisky Jack Daniel\'s','Jack Daniel\'s','ML',750,50);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (58,'Whisky Johnnie Walker Red Label','Johnnie Walker','ML',1000,70);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (59,'Whisky Johnnie Walker Black Label','Johnnie Walker','ML',1000,40);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (60,'Whisky Ballantine\'s','Ballantine\'s','ML',1000,60);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (61,'Whisky Chivas Regal','Chivas Brothers','ML',1000,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (62,'Whisky Jameson','Jameson Irish Whiskey','ML',750,50);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (63,'Whisky Glenfiddich 12 anos','Glenfiddich','ML',750,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (64,'Whisky Macallan','The Macallan Distillers','ML',750,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (65,'Whisky Talisker','Talisker Distillery','ML',700,25);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (66,'Whisky Lagavulin','Lagavulin Distillery','ML',750,15);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (67,'Whisky Laphroaig','Laphroaig Distillery','ML',700,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (68,'Whisky Glenlivet','The Glenlivet Distillery','ML',750,25);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (69,'Whisky Hibiki','Suntory','ML',700,35);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (70,'Whisky Nikka','Nikka Whisky Distilling Co.','ML',700,45);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (71,'Whisky Yamazaki','Suntory','ML',700,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (72,'Whisky Buffalo Trace','Buffalo Trace Distillery','ML',750,50);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (73,'Whisky Maker\'s Mark','Maker\'s Mark Distillery','ML',750,40);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (74,'Whisky Woodford Reserve','Woodford Reserve Distillery','ML',750,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (75,'Whisky Wild Turkey','Wild Turkey Distillery','ML',750,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (76,'Whisky Jim Beam','Jim Beam Brands Co.','ML',750,25);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (77,'Vodka Absolut','The Absolut Company','ML',750,50);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (78,'Vodka Smirnoff','Diageo','ML',1000,70);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (79,'Vodka Belvedere','LVMH','ML',1000,40);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (80,'Vodka Grey Goose','Bacardi','ML',1000,60);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (81,'Vodka Ketel One','Ketel One Distillery','ML',1000,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (82,'Vodka Cîroc','Diageo','ML',750,50);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (83,'Vodka Stolichnaya','SPI Group','ML',750,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (84,'Vodka Beluga','Mariinsk Distillery','ML',750,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (85,'Vodka Russian Standard','Russian Standard Vodka','ML',700,25);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (86,'Vodka Eristoff','Bacardi','ML',750,15);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (87,'Vodka Finlandia','Altia','ML',700,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (88,'Vodka Skyy','Campari Group','ML',750,25);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (89,'Vodka Reyka','William Grant & Sons','ML',700,35);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (90,'Vodka Absolut Elyx','The Absolut Company','ML',700,45);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (91,'Vodka Beluga Gold Line','Mariinsk Distillery','ML',700,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (92,'Vodka Grey Goose La Poire','Bacardi','ML',750,50);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (93,'Vodka Ketel One Botanical','Ketel One Distillery','ML',750,40);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (94,'Vodka Absolut Juice Pear & Elderflower','The Absolut Company','ML',750,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (95,'Vodka Crystal Head','Crystal Head Vodka','ML',750,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (96,'Vodka Svedka','Constellation Brands','ML',750,25);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (97,'Vinho tinto Château Margaux','Château Margaux','ML',750,10);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (98,'Vinho tinto Château Latour','Château Latour','ML',750,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (99,'Vinho tinto Château Lafite Rothschild','Château Lafite Rothschild','ML',750,15);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (100,'Vinho tinto Petrus','Petrus','ML',750,5);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (101,'Vinho tinto Vega Sicilia Único','Vega Sicilia','ML',750,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (102,'Vinho tinto Pingus','Pingus','ML',750,25);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (103,'Vinho tinto Ornellaia','Ornellaia','ML',750,35);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (104,'Vinho tinto Sassicaia','Tenuta San Guido','ML',750,40);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (105,'Vinho tinto Masseto','Masseto','ML',750,10);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (106,'Vinho branco Chardonnay','Domaine Leflaive','ML',750,15);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (107,'Vinho branco Sauvignon Blanc','Domaine de la Romanée-Conti','ML',750,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (108,'Vinho branco Riesling','Egon Müller-Scharzhof','ML',750,25);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (109,'Vinho branco Sauternes','Château d\'Yquem','ML',375,5);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (110,'Vinho rosé Domaines Ott','Domaines Ott','ML',750,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (111,'Vinho do Porto Graham\'s 40 anos','Graham\'s','ML',750,10);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (112,'Vinho do Porto Taylor\'s 40 anos','Taylor\'s','ML',750,15);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (113,'Vinho do Porto Quinta do Noval Nacional Vintage','Quinta do Noval','ML',750,5);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (114,'Vinho do Porto Dow\'s Vintage','Dow\'s','ML',750,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (115,'Vinho do Porto Warre\'s Vintage','Warre\'s','ML',750,25);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (116,'Gin Beefeater','Beefeater','ML',750,50);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (117,'Gin Bombay Sapphire','Bombay Sapphire','ML',750,70);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (118,'Gin Tanqueray','Tanqueray','ML',750,40);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (119,'Gin Hendrick\'s','Hendrick\'s','ML',750,60);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (120,'Gin Bulldog','Bulldog Gin Company','ML',750,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (121,'Gin Gordon\'s','Gordon\'s Gin','ML',750,50);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (122,'Gin Seagram\'s','Seagram\'s Gin','ML',750,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (123,'Gin Martin Miller\'s','Martin Miller\'s Gin','ML',700,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (124,'Gin Roku','Roku Gin','ML',700,25);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (125,'Gin Monkey 47','Monkey 47','ML',500,15);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (126,'Gin Aviation','Aviation Gin','ML',750,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (127,'Gin Plymouth','Plymouth Gin','ML',750,25);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (128,'Gin The Botanist','The Botanist Gin','ML',750,35);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (129,'Gin No. 3','No. 3 Gin','ML',700,45);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (130,'Gin Bluecoat','Bluecoat Gin','ML',750,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (131,'Gin G\'Vine Floraison','G\'Vine Gin','ML',750,50);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (132,'Gin Sipsmith London Dry','Sipsmith Gin','ML',750,40);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (133,'Gin Bulldog Bold','Bulldog Gin Company','ML',750,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (134,'Gin Brockmans','Brockmans Gin','ML',750,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (135,'Tequila Jose Cuervo Especial','Jose Cuervo','ML',750,50);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (136,'Tequila Patrón Silver','Patrón Spirits','ML',750,70);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (137,'Tequila Don Julio Blanco','Don Julio','ML',750,40);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (138,'Tequila Sauza Hornitos Plata','Sauza Tequila','ML',750,60);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (139,'Tequila 1800 Reposado','1800 Tequila','ML',750,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (140,'Tequila Olmeca Altos Plata','Olmeca Tequila','ML',750,50);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (141,'Tequila El Jimador Reposado','El Jimador','ML',750,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (142,'Tequila Casamigos Blanco','Casamigos Tequila','ML',750,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (143,'Tequila Herradura Silver','Herradura Tequila','ML',750,25);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (144,'Tequila Cazadores Blanco','Cazadores Tequila','ML',750,15);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (145,'Tequila Milagro Silver','Milagro Tequila','ML',750,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (146,'Tequila Avión Silver','Avión Tequila','ML',750,25);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (147,'Tequila Clase Azul Plata','Clase Azul Tequila','ML',750,25);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (148,'Tequila Corralejo Reposado','Corralejo Tequila','ML',750,35);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (149,'Tequila Fortaleza Blanco','Tequila Fortaleza','ML',750,45);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (150,'Tequila Casa Noble Crystal','Casa Noble Tequila','ML',750,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (151,'Tequila Espolòn Blanco','Espolòn Tequila','ML',750,50);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (152,'Tequila Maestro Dobel Silver','Maestro Dobel Tequila','ML',750,40);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (153,'Tequila Tres Generaciones Plata','Tres Generaciones Tequila','ML',750,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (154,'Tequila El Tesoro Platinum','Tequila El Tesoro','ML',750,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (155,'Champagne Veuve Clicquot Brut','Veuve Clicquot Ponsardin','ML',750,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (156,'Champagne Dom Perignon Brut Vintage','Moet & Chandon','ML',750,10);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (157,'Champagne Krug Grande Cuvee Brut','Krug','ML',750,5);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (158,'Champagne Louis Roederer Cristal','Louis Roederer','ML',750,15);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (159,'Champagne Bollinger R.D. Extra Brut','Bollinger','ML',750,10);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (160,'Champagne Taittinger Comtes de Champagne Blanc de Blancs','Taittinger','ML',750,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (161,'Champagne Laurent-Perrier Grand Siecle','Laurent-Perrier','ML',750,25);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (162,'Champagne Moet & Chandon Imperial Brut','Moet & Chandon','ML',750,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (163,'Champagne Perrier-Jouet Belle Epoque','Perrier-Jouet','ML',750,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (164,'Champagne Pol Roger Brut Reserve','Pol Roger','ML',750,15);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (165,'Champagne Ruinart Blanc de Blancs','Ruinart','ML',750,25);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (166,'Champagne Veuve Clicquot La Grande Dame','Veuve Clicquot Ponsardin','ML',750,10);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (167,'Champagne Moet & Chandon Rose Imperial','Moet & Chandon','ML',750,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (168,'Champagne Louis Roederer Cristal Rose','Louis Roederer','ML',750,5);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (169,'Champagne Piper-Heidsieck Rare Brut','Piper-Heidsieck','ML',750,10);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (170,'Champagne Charles Heidsieck Brut Reserve','Charles Heidsieck','ML',750,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (171,'Champagne Veuve Clicquot Demi-Sec','Veuve Clicquot Ponsardin','ML',750,15);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (172,'Champagne Gosset Grand Reserve Brut','Gosset','ML',750,25);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (173,'Champagne Moet & Chandon Nectar Imperial','Moet & Chandon','ML',750,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (174,'Champagne Krug Rose','Krug','ML',750,5);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (175,'Rum Bacardi Carta Blanca','Bacardi','ML',750,50);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (176,'Rum Captain Morgan','Captain Morgan','ML',750,70);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (177,'Rum Havana Club 3 anos','Havana Club','ML',700,40);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (178,'Rum Malibu','Pernod Ricard','ML',700,60);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (179,'Rum Myers\'s','Myers\'s Rum','ML',750,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (180,'Rum Sailor Jerry','Sailor Jerry Ltd.','ML',750,50);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (181,'Rum Appleton Estate','Appleton Estate','ML',700,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (182,'Rum Ron Zacapa 23 anos','Zacapa','ML',750,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (183,'Rum Mount Gay','Mount Gay Distilleries','ML',700,25);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (184,'Rum Angostura','Angostura Holdings','ML',750,15);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (185,'Rum Ron Barceló','Barceló','ML',700,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (186,'Rum Brugal','Brugal','ML',750,25);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (187,'Rum Flor de Caña','Flor de Caña','ML',700,35);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (188,'Rum Diplomático','Destilerías Unidas S.A.','ML',700,45);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (189,'Rum Gosling\'s Black Seal','Gosling Brothers Ltd.','ML',750,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (190,'Rum Matusalem','Matusalem & Company','ML',750,40);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (191,'Rum Ron del Barrilito','Ron del Barrilito','ML',750,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (192,'Rum Wray & Nephew','J. Wray and Nephew Ltd.','ML',700,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (193,'Rum Cacique','Destilerías Unidas S.A.','ML',750,25);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (194,'Cachaça 51','Companhia Müller de Bebidas','ML',1000,80);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (195,'Cachaça Sagatiba','Pernod Ricard','ML',700,50);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (196,'Cachaça Ypióca','Ypióca Agroindustrial','ML',1000,70);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (197,'Cachaça Velho Barreiro','Indústria e Comércio Velho Barreiro','ML',1000,60);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (198,'Cachaça Pirassununga 51','Companhia Müller de Bebidas','ML',1000,90);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (199,'Cachaça Weber Haus','Weber Haus Destilaria Artesanal','ML',700,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (200,'Cachaça Leblon','Cachaça Leblon Ltda','ML',700,40);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (201,'Cachaça Nêga Fulô','Fazenda Soledade Indústria e Comércio LTDA','ML',700,25);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (202,'Cachaça Seleta','Engenho Camargo Corrêa','ML',700,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (203,'Cachaça Magnífica','Destilaria Magnífica','ML',700,15);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (204,'Cachaça 51','Companhia Müller de Bebidas','ML',1000,80);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (205,'Cachaça Sagatiba','Pernod Ricard','ML',700,50);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (206,'Cachaça Ypióca','Ypióca Agroindustrial','ML',1000,70);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (207,'Cachaça Velho Barreiro','Indústria e Comércio Velho Barreiro','ML',1000,60);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (208,'Cachaça Pirassununga 51','Companhia Müller de Bebidas','ML',1000,90);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (209,'Cachaça Weber Haus','Weber Haus Destilaria Artesanal','ML',700,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (210,'Cachaça Leblon','Cachaça Leblon Ltda','ML',700,40);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (211,'Cachaça Nêga Fulô','Fazenda Soledade Indústria e Comércio LTDA','ML',700,25);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (212,'Cachaça Seleta','Engenho Camargo Corrêa','ML',700,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (213,'Cachaça Magnífica','Destilaria Magnífica','ML',700,15);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (214,'Skol Pilsen','Ambev','ML',350000,100);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (215,'Brahma Pilsen','Ambev','ML',350000,120);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (216,'Bohemia','Ambev','ML',355000,80);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (217,'Antarctica Pilsen','Ambev','ML',350000,90);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (218,'Original','Ambev','ML',600000,70);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (219,'Serramalte','Ambev','ML',600000,60);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (220,'Heineken','Heineken','ML',355000,50);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (221,'Stella Artois','AB InBev','ML',275000,40);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (222,'Corona Extra','Grupo Modelo','ML',355000,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (223,'Budweiser','AB InBev','ML',355000,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (224,'Colorado','Cervejaria Colorado','ML',600000,10);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (225,'Eisenbahn','Cervejaria Sudbrack','ML',600000,15);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (226,'Patagônia','Cervecería Patagonia','ML',740000,25);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (227,'Baden Baden','Cervejaria Baden Baden','ML',600000,20);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (228,'Wäls','Cervejaria Wäls','ML',600000,30);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (229,'Bohemia Confraria','Ambev','ML',600000,40);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (230,'Leffe Blonde','AB InBev','ML',330000,35);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (231,'Paulaner','Paulaner Brauerei GmbH & Co. KG','ML',500000,45);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (232,'Franziskaner','Spaten-Franziskaner-Bräu GmbH','ML',500000,55);
INSERT INTO `` (`id_produto`,`nome_produto`,`fabricante`,`tipo_volume`,`qtd_volume`,`qtd_estoque`) VALUES (233,'Erdinger Weissbier','Erdinger Weissbräu','ML',500000,50);
